### ISSUE TITLE
Possible memory leak in detail screen

### ISSUE THREAD

**Issue by dkhamsing** [Say-Their-Name/say-their-names-ios#225]
Here's a video of Instruments.. it is not 100% consistent. Could it be related to LinkPresentation?

https://imgur.com/xoLYAao

Xcode: 11.5
Commit: 6d5e76b40e4d9b0a41bf810fc2a726aeb40b426d

**Comment by ohwhen** [comment]
Just ran Instruments, it seems there's some metadata that is retained but the majority of the memory is released once you go to another viewcontroller or when the app goes to background. Nothing too alarming imho.

![Screen Shot 2020-07-11 at 12 27 46 PM](https://user-images.githubusercontent.com/301029/87228847-f3f71b00-c371-11ea-8f32-2c0a428318c4.png)
