### ISSUE TITLE
Tapping on #BLACKLIVESMATTER takes a user to a victim page

### ISSUE THREAD

**Issue by hybridcattt** [Say-Their-Name/say-their-names-ios#227]
## Summary 

Tapping on #BLACKLIVESMATTER on the home screen banner takes the user to the first victim's page. 

## Expected behaviour

Nothing should happen when the banner is tapped. 

Moved from Trello:
https://trello.com/c/jLMl2Qyf/185-fix-onpress-handler-of-hero-cell-on-home-page

**Comment by jacobrozell** [comment]
The issue is that there is no check for what section you selected the cell in. So when you select the #BLACKLIVESMATTER banner it has an index of 0 in section 0, but will present the victim that is at index of 0 in section 1.
