### ISSUE TITLE
Finalize Portugese localization

### ISSUE THREAD

**Issue by hybridcattt** [Say-Their-Name/say-their-names-ios#231]
## Summary

The project's Portugese localization is currently partially done. A handful of new keys have been added recently and they need translations. 

To work on translations, you'd need to get access to the localization tool. It's easy to get, @hybridcattt is currently managing access to the tool. Technical details of the workflow are currently described [here on slack](https://saytheirnames.slack.com/archives/C014X94AEUR/p1591983765022900).

## How does it improve the project?

The project is international and the more languages we support, the further is the reach. 

Moved from Trello:
https://trello.com/c/914zREis/178-complete-portugese-localisation

**Comment by Pancreax** [comment]
Hi! I would like to work on this issue! :)

**Comment by hybridcattt** [comment]
@Pancreax 🎉 
Let me know if you need any help or have any questions!

**Comment by Pancreax** [comment]
@hybridcattt nice! I just created my account on `localise.biz/guilhermedvae`. Could you please add me as a translator?

**Comment by hybridcattt** [comment]
@Pancreax of course! Could you give me your email address? It doesn't offer to find users by username.

**Comment by Pancreax** [comment]
@hybridcattt My email is guilhermedvae@gmail.com

**Comment by hybridcattt** [comment]
@Pancreax Done!
