### ISSUE TITLE
Issue with selection of location tabs on home controller

### ISSUE THREAD

**Issue by Sharkesm** [Say-Their-Name/say-their-names-ios#234]
## Summary

When location tabs are clicked, the selection doesn't work correctly. 
Need to maintain a source of truth for what filter is currently selected - a variable + reflect in the UI accordingly. 
In the future, we will be updating displayed data using this filter property, but for now, it can just do nothing and only update the selected filter visually. 

## How does it improve the project?

Allow users to filter content based on locations 

Moved from Trello:
https://trello.com/c/TOHJFEI6/90-fix-selection-of-location-tabs-on-home-controller

**Comment by furrki** [comment]
I don't see any location filter on home page. Shouldn't this issue be closed?
