### ISSUE TITLE
Enable and reveal search UI when search button is pressed 

### ISSUE THREAD

**Issue by Sharkesm** [Say-Their-Name/say-their-names-ios#235]
## Summary

It seems like after the most recent changes to the UI on HomeController the Search UI is hidden under the CollectionView use for the Home Screen.

## How does it improve the project?

Allows users to filter content on a specified UI element 

Moved from Trello:
https://trello.com/c/E6Spnqn9/111-pressing-the-search-button-on-home-page-doesnt-reveal-the-search-ui-paused

**Comment by Kilo-Loco** [comment]
Addressed in [pr 241](https://github.com/Say-Their-Name/say-their-names-ios/pull/241)
