### ISSUE TITLE
Hide donations filters when there are none values

### ISSUE THREAD

**Issue by Sharkesm** [Say-Their-Name/say-their-names-ios#236]
## Summary

Currently, we are showing filter options on donations and petitions screens however the filter element shouldn't be visible if there are no values since it returns an empty result. We could simply add an empty state for this case to be displayed back to the users. 

**Note:** this applies only when filters feature is enabled, which it is currently not. 

## How does it improve the project?

Improves UX behavior and quick feedback to the users in case of empty result as response.   

Moved from Trello:
https://trello.com/c/uCNeeEYr/126-hide-donations-filters-when-there-are-none-values

Related issue: 
https://github.com/Say-Their-Name/say-their-names-web/issues/98

**Comment by Drag0ndust** [comment]
@Sharkesm, @hybridcattt: Is this still an issue? At the moment I can't see the filter options on that screens.
Are there further information available on this topic?

**Comment by furrki** [comment]
Shouldnt this issue be closed?

**Comment by hybridcattt** [comment]
Let's keep it open for now, in case filters feature is worked on again
