### ISSUE TITLE
Fix accessibility of the carousel on home

### ISSUE THREAD

**Issue by Sharkesm** [Say-Their-Name/say-their-names-ios#237]
## Summary

The carousel navigation element on the Home screen requires accessibility 

## How does it improve the project?

Transform an existing app to make it more accessible for people with visual/other disabilities.

Moved from Trello:
https://trello.com/c/PjqrRwX1/89-fix-accessibility-of-the-carousel-on-home

**Comment by hybridcattt** [comment]
Resolved by #247
