### ISSUE TITLE
Finalize Hebrew localization 

### ISSUE THREAD

**Issue by helloITdepartment** [Say-Their-Name/say-their-names-ios#238]
## Summary

The project's Hebrew localization is currently partially done. 

To work on translations, you'd need to get access to the localization tool. It's easy to get, @hybridcattt is currently managing access to the tool. Technical details of the workflow are currently described [here on slack](https://saytheirnames.slack.com/archives/C014X94AEUR/p1591983765022900).

## How does it improve the project?

The project is international and the more languages we support, the further is the reach.

**Comment by hybridcattt** [comment]
Resolved by #256
