### ISSUE TITLE
Placeholder image for news/ media cells if loading fails

### ISSUE THREAD

**Issue by ScruffyHipster** [Say-Their-Name/say-their-names-ios#239]
Currently if media fails to load the cell will remain a block colour atm. Use a placeholder to negate this. Also if the user taps this cell it will take the user out of the app to a broken link (example: DAVIS MCATEE 2nd link). 

**Suggestion** Maybe preventing the cell from being selected by setting the isUserInteractionEnabled to false if download results in a fail. However, I'm not sure if this would result in poor user experience. Possibly a second ticket.

Steps to replicate:
- Open app
- Select DAVID MCATEE
- Scroll down to news
- Wait for spinner to disappear after failed load.

**Comment by Mobo24** [comment]
the block color is the placeholder

**Comment by hybridcattt** [comment]
Resolved by #246 🙌
