### ISSUE TITLE
Donation button should be hidden if no donation information exists.

### ISSUE THREAD

**Issue by karnett** [Say-Their-Name/say-their-names-ios#240]
Upon selecting a person from the home screen, you will see the donation button show. If there is no donation information, tapping the button will not do anything. Found with Darren Cumberbatch's profile.

What is expected of this work?
We should only show the button if there is an action to take, ie: donation information exists.

How does this improve the project?
Improve user experience by ensuring when they tap there button there is an action to take.

Are there any code samples or examples you can think of, in the current repo or in outside repos?
Within the donation block, there is already code to see if donations exist. We need to move it to apply to adding the view instead, not just when the button is tapped.

Trello:
https://trello.com/c/msA5doRU

**Comment by Mobo24** [comment]
Created a pull request for this card.

**Comment by hybridcattt** [comment]
Addressed by #245
