### ISSUE TITLE
[BUG] Join our Slack Channel link is expired 

### ISSUE THREAD

**Issue by jacobrozell** [Say-Their-Name/say-their-names-ios#243]
Slack link is expired for the `Join our Slack Channel` button in the `About` tab.

<img width="345" alt="Screen Shot 2020-08-03 at 6 20 10 PM" src="https://user-images.githubusercontent.com/27265631/89236372-fe45b700-d5b5-11ea-8b60-6853a071d446.png">

**Comment by jacobrozell** [comment]
Could potentially fix this, but the link is also expired for the `CONTRIBUTING.md` so I haven't been able to join the slack myself.

**Comment by hybridcattt** [comment]
Hmmm, it's a good catch. I've updated the link in the guide couple weeks ago, it must have expired again. I was under the impression it's an indefinite one. Let me check on slack if we have a new one

**Comment by hybridcattt** [comment]
This is the new link that never expires: https://bit.ly/join-our-saytheirnames-slack
