### ISSUE TITLE
Turkish Localization 🇹🇷

### ISSUE THREAD

**Issue by furrki** [Say-Their-Name/say-their-names-ios#260]
**Summary**

The project's Hebrew localization is currently partially done.

To work on translations, you'd need to get access to the localization tool. It's easy to get, @hybridcattt is currently managing access to the tool. Technical details of the workflow are currently described here on slack.

**How does it improve the project?**

The project is international and the more languages we support, the further is the reach.

**Comment by hybridcattt** [comment]
@furrki it's a good idea. Feel free to recreate the issue again if you want, and let us know if you need any help!
