### ISSUE TITLE
Remove the spaces in the paths

### ISSUE THREAD

**Issue by rodericj** [Say-Their-Name/say-their-names-ios#33]
When working in the command line or some CI setups I've had some issues with spaces in paths. I'm proposing that we remove the spaces in the project before too many folks get involved. Let me know your thoughts, I can throw together a PR if you think it's reasonable.

**Comment by hybridcattt** [comment]
@rodericj  That is a great point, definitely worth doing. 
Our community lives in a slack org + we use Trello for project management, you are very welcome to join! Alternatively feel free to just fork the repo and make a one-off contribution. 
Either way thanks for being here 🙌

**Comment by rodericj** [comment]
I see what you mean about trello. That’s why there are no GitHub issues.
