### ISSUE TITLE
Downloaded and looked over this project and this are my questions.

### ISSUE THREAD

**Issue by nedimf** [Say-Their-Name/say-their-names-ios#60]
- Why Alamofire when URLSession can done the job as effectively and it will not cluter the pod?
- How you gonna implement sharing  (universal links)?
- What are things that is worked on?

Happy to contribute the cause.

**Comment by rodericj** [comment]
Check out https://github.com/Say-Their-Name/say-their-names-ios/blob/development/CONTRIBUTING.md. From there you can get into the slack and the trello and the other questions should be answered through those channels.
